-- Script para limpiar tablas antes de la migración
TRUNCATE TABLE fvpos_vat CASCADE;
TRUNCATE TABLE fvpos_vat_condition CASCADE;
TRUNCATE TABLE fvpos_sale_condition CASCADE;
TRUNCATE TABLE fvpos_receipt_type CASCADE;
TRUNCATE TABLE fvpos_brand CASCADE;
TRUNCATE TABLE fvpos_credit_card CASCADE;
TRUNCATE TABLE fvpos_debit_card CASCADE;
TRUNCATE TABLE fvpos_employee CASCADE;
TRUNCATE TABLE fvpos_customer CASCADE;
TRUNCATE TABLE fvpos_supplier CASCADE;
TRUNCATE TABLE fvpos_product_category CASCADE;
TRUNCATE TABLE fvpos_product CASCADE;
TRUNCATE TABLE fvpos_product_photo CASCADE;
TRUNCATE TABLE fvpos_supplier_for_product CASCADE;
TRUNCATE TABLE fvpos_price_list CASCADE;
TRUNCATE TABLE fvpos_product_price CASCADE;
TRUNCATE TABLE fvpos_order CASCADE;
TRUNCATE TABLE fvpos_order_line CASCADE;
TRUNCATE TABLE fvpos_purchase CASCADE;
TRUNCATE TABLE fvpos_purchase_line CASCADE;
TRUNCATE TABLE fvpos_budget CASCADE;
TRUNCATE TABLE fvpos_budget_line CASCADE;
TRUNCATE TABLE fvpos_cash_operation CASCADE;
TRUNCATE TABLE fvpos_customer_on_account_op CASCADE;
TRUNCATE TABLE fvpos_supplier_on_account_op CASCADE;
TRUNCATE TABLE fvpos_nota_de_credito CASCADE;
TRUNCATE TABLE fvpos_app_config CASCADE;
TRUNCATE TABLE fvpos_workstation_config CASCADE;

-- Reiniciar las secuencias
ALTER SEQUENCE IF EXISTS fvpos_vat_vat_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_vat_condition_condition_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_sale_condition_condition_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_receipt_type_receipt_type_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_brand_brand_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_credit_card_card_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_debit_card_card_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_employee_employee_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_customer_customer_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_supplier_supplier_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_product_category_category_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_product_product_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_price_list_list_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_order_order_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_purchase_purchase_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_budget_budget_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_cash_operation_cash_operation_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_nota_de_credito_nota_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_app_config_app_config_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS fvpos_workstation_config_workstation_config_id_seq RESTART WITH 1; 