-- Modificar columnas numéricas de DECIMAL a DOUBLE PRECISION

-- FVPOS_PRODUCT_PRICE
ALTER TABLE fvpos_product_price 
    ALTER COLUMN cost_price TYPE DOUBLE PRECISION,
    ALTER COLUMN gross_margin TYPE DOUBLE PRECISION,
    ALTER COLUMN internal_tax TYPE DOUBLE PRECISION,
    ALTER COLUMN net_price TYPE DOUBLE PRECISION,
    ALTER COLUMN previous_selling_price TYPE DOUBLE PRECISION,
    ALTER COLUMN selling_price TYPE DOUBLE PRECISION;

-- FVPOS_ORDER
ALTER TABLE fvpos_order
    ALTER COLUMN payment_cash_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_check_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_credit_card_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_debit_card_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN discount_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN discount_percent TYPE DOUBLE PRECISION,
    ALTER COLUMN inner_taxes TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_net_cash_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_net_check_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_net_credit_card_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_net_debit_card_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_net_on_account_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_net_tickets_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_on_account_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN reduced_vat_value TYPE DOUBLE PRECISION,
    ALTER COLUMN standard_vat_value TYPE DOUBLE PRECISION,
    ALTER COLUMN subtotal TYPE DOUBLE PRECISION,
    ALTER COLUMN surcharge_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN surcharge_percent TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_tickets_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN total TYPE DOUBLE PRECISION;

-- FVPOS_ORDER_LINE
ALTER TABLE fvpos_order_line
    ALTER COLUMN cost_price TYPE DOUBLE PRECISION,
    ALTER COLUMN internal_tax TYPE DOUBLE PRECISION,
    ALTER COLUMN price TYPE DOUBLE PRECISION,
    ALTER COLUMN profit_margin TYPE DOUBLE PRECISION,
    ALTER COLUMN qty TYPE DOUBLE PRECISION,
    ALTER COLUMN vat_value TYPE DOUBLE PRECISION;

-- FVPOS_PURCHASE
ALTER TABLE fvpos_purchase
    ALTER COLUMN subtotal TYPE DOUBLE PRECISION,
    ALTER COLUMN inner_taxes TYPE DOUBLE PRECISION,
    ALTER COLUMN total TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_card_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_cash_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_on_account_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_check_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN payment_tickets_amt TYPE DOUBLE PRECISION,
    ALTER COLUMN standard_vat_value TYPE DOUBLE PRECISION,
    ALTER COLUMN reduced_vat_value TYPE DOUBLE PRECISION;

-- FVPOS_PURCHASE_LINE
ALTER TABLE fvpos_purchase_line
    ALTER COLUMN price TYPE DOUBLE PRECISION,
    ALTER COLUMN qty TYPE DOUBLE PRECISION,
    ALTER COLUMN vat_value TYPE DOUBLE PRECISION;

-- FVPOS_BUDGET
ALTER TABLE fvpos_budget
    ALTER COLUMN inner_taxes TYPE DOUBLE PRECISION,
    ALTER COLUMN reduced_vat_value TYPE DOUBLE PRECISION,
    ALTER COLUMN standard_vat_value TYPE DOUBLE PRECISION,
    ALTER COLUMN subtotal TYPE DOUBLE PRECISION,
    ALTER COLUMN total TYPE DOUBLE PRECISION;

-- FVPOS_BUDGET_LINE
ALTER TABLE fvpos_budget_line
    ALTER COLUMN price TYPE DOUBLE PRECISION,
    ALTER COLUMN qty TYPE DOUBLE PRECISION,
    ALTER COLUMN vat_value TYPE DOUBLE PRECISION;

-- FVPOS_CASH_OPERATION
ALTER TABLE fvpos_cash_operation
    ALTER COLUMN amount TYPE DOUBLE PRECISION;

-- FVPOS_CUSTOMER_ON_ACCOUNT_OP
ALTER TABLE fvpos_customer_on_account_op
    ALTER COLUMN amount TYPE DOUBLE PRECISION;

-- FVPOS_SUPPLIER_ON_ACCOUNT_OP
ALTER TABLE fvpos_supplier_on_account_op
    ALTER COLUMN amount TYPE DOUBLE PRECISION;

-- FVPOS_NOTA_DE_CREDITO
ALTER TABLE fvpos_nota_de_credito
    ALTER COLUMN product_price TYPE DOUBLE PRECISION,
    ALTER COLUMN product_qty TYPE DOUBLE PRECISION,
    ALTER COLUMN product_vat_value TYPE DOUBLE PRECISION;

-- FVPOS_APP_CONFIG
ALTER TABLE fvpos_app_config
    ALTER COLUMN cash_amount TYPE DOUBLE PRECISION;

-- FVPOS_WORKSTATION_CONFIG
ALTER TABLE fvpos_workstation_config
    ALTER COLUMN cash_amount TYPE DOUBLE PRECISION; 